<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TaskrApi\TaskrApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.MsSql" Version="4.13.0" />
    <PackageReference Include="Respawn" Version="7.0.0" />
  </ItemGroup>
</Project>