<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TaskrApi\TaskrApi.csproj" />
    <ProjectReference Include="..\TestInfrastructure\TestInfrastructure.csproj" />
  </ItemGroup>

</Project>
